services:
  postgre:
    image: postgres:latest
    restart: always
    container_name: postgre
    hostname: postgre
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dealls-date
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - ./volumes/postgre/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379